### PR TITLE
add a Sealnado countdown from the Island Adventure mod

### PR DESCRIPTION
**Pull request by BB-GOAT**

### CODE REVIEW

**Comment by penguin0616** [comment]
As a rule of thumb, I don't handle third party mod support within Insight.
So I can't accept this PR.

However, I've reached out to the Island Adventures team to see if they're willing to add the Insight support within their mod.

**Comment by 3242394814** [comment]
> 根据经验，我不在 Insight 中处理第三方 mod 支持。所以我不能接受这个公关。
> 
> 但是，我已经联系了 Island Adventures 团队，看看他们是否愿意在他们的模组中添加 Insight 支持。

ummm, I see that the countdown for other things is added in Insight, such as the countdown for volcanic eruptions. Why doesn't this work😢

**Comment by BB-GOAT** [comment]
> As a rule of thumb, I don't handle third party mod support within Insight. So I can't accept this PR.
> 
> However, I've reached out to the Island Adventures team to see if they're willing to add the Insight support within their mod.

ummm, I see that the countdown for other things is added in Insight, such as the countdown for volcanic eruptions. Why don't handle this😢

**Comment by BB-GOAT** [comment]
> As a rule of thumb, I don't handle third party mod support within Insight. So I can't accept this PR.
> 
> However, I've reached out to the Island Adventures team to see if they're willing to add the Insight support within their mod.

The island adventure team is willing to add this, I asked them. If you don't accept this PR now, then I can only add it in Island Adventure

**Comment by penguin0616** [comment]
> > As a rule of thumb, I don't handle third party mod support within Insight. So I can't accept this PR.
> > However, I've reached out to the Island Adventures team to see if they're willing to add the Insight support within their mod.
> 
> ummm, I see that the countdown for other things is added in Insight, such as the countdown for volcanic eruptions. Why don't handle this😢

Volcanic eruptions are handled as part of Insight for Don't Starve, not Island Adventures for Don't Starve Together.

Sealnado cooldown is also handled part of Insight for Don't Starve, because it's meant to. It wasn't meant to handle Sealnado cooldown for Island Adventures.

If Insight is properly working for something from Island Adventures, then it's a pleasant coincidence that the Island Adventures implementation of that thing works the same as Don't Starve, so I don't need to do anything.

**Comment by BB-GOAT** [comment]
> >> As a rule of thumb, I don't handle third party mod support within Insight. So I can't accept this PR.
> > > However, I've reached out to the Island Adventures team to see if they're willing to add the Insight support within their mod.
> > 
> > 
> > ummm, I see that the countdown for other things is added in Insight, such as the countdown for volcanic eruptions. Why don't handle this😢
> 
> Volcanic eruptions are handled as part of Insight for Don't Starve, not Island Adventures for Don't Starve Together.
> 
> Sealnado cooldown is also handled part of Insight for Don't Starve, because it's meant to. It wasn't meant to handle Sealnado cooldown for Island Adventures.
> 
> If Insight is properly working for something from Island Adventures, then it's a pleasant coincidence that the Island Adventures implementation of that thing works the same as Don't Starve, so I don't need to do anything.

Oh, it's just a coincidence 😲 Okay, I'll go modify the island adventure later😕

**Pull request closed without merging**
