### PR TITLE
Russian Localization

### PR DESCRIPTION
**Pull request by LehaSex**
Hi, I added a Russian translation to your mod

### CODE REVIEW

**Comment by LehaSex** [comment]
Idk why, but it does not appear in the language selection

**Comment by penguin0616** [comment]
It doesn't show up because you didn't add it as an option for the language config.

Thank you for your contribution! Would you like to be added to the translation credits in the mod description?

**Comment by LehaSex** [comment]
Yes, it would be very cool!

> Thank you for your contribution! Would you like to be added to the translation credits in the mod description?

**Comment by penguin0616** [comment]
Sounds good, you'll be added in the description in Insight update 4.6.0

**Comment by penguin0616** [comment]
> Yes, it would be very cool!
> 
> > Thank you for your contribution! Would you like to be added to the translation credits in the mod description?

@LehaSex Can you link me your steam profile?

**Comment by LehaSex** [comment]
> > Yes, it would be very cool!
> > > Thank you for your contribution! Would you like to be added to the translation credits in the mod description?
> 
> @LehaSex Can you link me your steam profile?

Hi, sorry for the wait. Here is my link https://steamcommunity.com/id/lehasex/

**Comment by penguin0616** [comment]
Added to the description, thanks.

**Pull request merged**
