### PR TITLE
Update chinese.lua

### PR DESCRIPTION
**Pull request by lloydev**
- Translated untranslated strings, corrected some translation
- Removed unnecessary Chinese punctuation and white space

### CODE REVIEW

**Comment by penguin0616** [comment]
Hi!
I'm really sorry for leaving you without a response for so long. Development has been rather unsteady.
Thank you for taking the time to provide some translations and corrections! I appreciate it.

I'm not able to directly accept this pull since there's been very significant changes to how Insight does localization, and you shouldn't have to deal with making the translations work on the new system.
I'll have to add them in manually, which will be fun and time consuming.

I'll close this pull & let you know when they are incorporated.

**Comment by lloydev** [comment]
OK. Thank you for your hard work!

**Comment by penguin0616** [comment]
@lloydev Okay, the changes have been incorporated and will be included in the next Steam release.
Do you want to be included in the translation credits? If so, how do you want credit? Steam account, GitHub account, something else?

**Comment by lloydev** [comment]
No, thanks. I just made a small contribution. This mod helps me a lot when playing the game, thanks again for your efforts to make it increasingly useful.

**Comment by penguin0616** [comment]
Alright, understood. Thanks again!

**Pull request closed without merging**
